---
sidebar: sidebar 
permalink: add-components-to-search-criteria.html 
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, Active IQ, Interop, Advisor, tool 
summary: 검색 텍스트 상자 또는 고급 검색을 사용하여 검색 조건에 구성 요소를 추가할 수 있습니다. 
---
= 검색 조건에 부품 추가
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
검색 텍스트 상자 또는 * 고급 검색 * 을 사용하여 검색 조건에 구성 요소를 추가할 수 있습니다.

.이 작업에 대해
검색 조건에 추가할 구성 요소를 알고 있으면 검색 텍스트 상자에 구성 요소 이름을 입력할 수 있습니다. 검색 조건에 추가할 구성 요소를 잘 모르는 경우 * 고급 검색 * 을 사용할 수 있습니다.

검색 기준에 포함된 구성 요소를 지우려면 오른쪽 위 모서리에 있는 * Clear All * 을 클릭합니다.

.단계
. 상호 운용성 매트릭스 툴 홈 페이지에서 검색 텍스트 상자에 구성 요소 이름을 입력하여 해당 구성 요소에 대해 가능한 일치 항목을 확인합니다.
+
.. 검색 조건에 구성 요소를 포함하려면 * 추가 * 를 클릭합니다.
.. 여러 범주의 구성 요소를 검색 조건에 포함하려면 * 추가 * 를 클릭합니다.
.. 일치 항목 모두 표시 * 를 클릭하면 IMT에서 검색 기준에 추가 구성 요소를 포함할 수 있는 * 고급 검색 * 을 표시합니다.


. 선택 사항. 고급 검색 * 을 사용하여 검색 조건에 구성 요소를 포함할 수 있습니다.
+
.. 고급 검색 * 을 클릭합니다.
.. 고급 검색* 창의 왼쪽 창에서 범주 또는 솔루션을 선택합니다.
.. 오른쪽 창에서 검색 조건에 추가할 구성 요소를 식별하고 * 추가 * 를 클릭합니다.
.. Advanced Search * 창에 키워드를 입력합니다.




검색 옵션으로 키워드를 활성화할 수 있습니다. 활성화된 경우 해당 행과 연결된 키워드를 사용하여 하나 이상의 행을 검색할 수 있습니다. 또한 * 고급 검색 * 창에서 검색 텍스트 상자를 사용하여 특정 구성 요소를 검색할 수도 있습니다. 고급 검색*을 사용하여 추가한 구성 요소를 제거하려면 오른쪽 창에서 * 제거 * 를 클릭합니다.



== 결과

검색 조건에 부품을 포함하면 * 검색 기준 * 아래 오른쪽 창에 부품이 표시됩니다.
