---
sidebar: sidebar 
permalink: index.html 
keywords: interoperability matrix tool, imt, ONTAP SAN Host Simplified 
summary: 'NetApp 상호 운용성 매트릭스 툴(IMT) 은 웹 기반 애플리케이션입니다. IMT를 사용하면 NetApp에서 지정한 표준 및 요구 사항을 충족하는 NetApp 제품 및 구성 요소의 구성을 검색할 수 있습니다.' 
---
= 상호 운용성 매트릭스 툴 개요
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp 상호 운용성 매트릭스 툴(IMT) 은 웹 기반 애플리케이션입니다. IMT를 사용하면 NetApp에서 지정한 표준 및 요구 사항을 충족하는 NetApp 제품 및 구성 요소의 구성을 검색할 수 있습니다. IMT는 구성 리포지토리를 유지하고 지원되는 구성 정보에 쉽게 액세스할 수 있는 사용자 친화적 인터페이스를 제공합니다.

NetApp 지원 사이트에서 다음 표준 브라우저 중 하나를 사용하여 IMT에 액세스할 수 있습니다.

* Windows의 경우:
+
** Chrome N 및 N-1
** Mozilla Firefox N 및 N-1
+

NOTE: N은 최신 버전을 나타냅니다.

** Internet Explorer 11 및 Edge


* Mac의 경우:
+
** Chrome N 및 N-1
** Mozilla Firefox N 및 N-1
** Safari 8 이상


+

NOTE: 상호 운용성 매트릭스 툴은 특정 사용 사례를 간소화하기 위해 기준이 있는 URL 링크를 사용할 수 있습니다. 다른 도구의 링크를 클릭하여 IMT를 열면 솔루션과 특정 구성 요소가 미리 선택되어 있는 홈 페이지가 아닌 놀이터 페이지에 표시될 수 있습니다.





== 상호 운용성 매트릭스 툴을 사용해 보십시오

IMT(상호 운용성 매트릭스 툴)는 다양한 솔루션, 구성, 구성 요소 및 범주를 사용하여 제품의 호환성을 검색하는 데 사용하는 웹 기반 애플리케이션입니다.

이 도구는 탐색과 명확성을 위해 * Enter Criteria *, * Refine Search Criteria * 및 * Results * 의 세 페이지로 구성됩니다. 첫 페이지에 검색 기준을 입력해야 합니다. 검색 기준에 따라 * 검색 기준 구체화 * 페이지에서 제품의 호환성을 확인할 수 있습니다. 이 항목에서는 IMT 사용 방법을 간략하게 설명합니다.

결과 * 페이지에서 결과를 볼 수 있습니다. 이 도구를 사용하여 부품을 검색하고, 선택하고, 기준을 작성하고, 제품의 호환성을 확인할 수 있습니다.

다음과 같은 작업을 수행할 수 있습니다.

[cols="25,65"]
|===
| 이 페이지 사용 중... | 이러한 작업을 수행할 수 있습니다... 


| 기준을 입력합니다 | 검색 기준을 입력하고 솔루션, 구성 요소, 구성 및 범주를 검색합니다. 솔루션 이름을 알고 있는 경우 * ONTAP SAN 호스트 간소화 * 또는 * 솔루션 검색 * 기능을 사용하여 솔루션을 검색할 수 있습니다. 구성 요소 이름을 알고 있는 경우 * 목록 및 찾기 * 또는 * 고급 검색 * 기능을 사용하여 구성 요소를 검색할 수 있습니다. 


| 검색 기준을 구체화합니다 | 제품의 호환 솔루션, 구성 요소, 구성 및 범주에 대한 보다 확실한 예 또는 아니요를 찾아보십시오. 첫 페이지에 입력한 초기 기준을 * 기준 변경 * 또는 * 다른 방법 시도 * 를 사용하여 변경할 수 있습니다. 각 범주의 부품에 필터를 적용하여 제품에 가장 적합한 구성을 찾습니다. 모두 지우기 * 또는 * 실행 취소 * 아이콘을 사용하여 적용한 필터를 제거합니다. 


| 결과 | 두 번째 페이지의 * 계속 *, *> * 아이콘 또는 분할자를 클릭한 후 * 결과 * 페이지를 확인합니다. 구성의 구성 요소, 노트 및 기록 세부 정보를 보고, 검색 결과를 정렬하고, 선택한 검색 기준을 보고, 검색 기준을 수정하고, 검색 결과를 필터링하고, 검색 결과를 Microsoft Excel 시트로 내보낼 수 있습니다. 
|===


== 상호 운용성 매트릭스 툴 홈 페이지를 사용하십시오

상호 운용성 매트릭스 툴(IMT) 홈 페이지에서 * ONTAP SAN 호스트 간소화 *, * 솔루션 검색, 목록 및 찾기 * 및 * 고급 검색 * 을 사용할 수 있습니다.

기본 * 별표로 설정 을 사용하여 이러한 옵션을 기본 검색으로 설정할 수 있습니다. 옵션 중 하나를 클릭하면 관련 페이지가 열려 호환 가능한 구성을 탐색할 수 있습니다.


NOTE: 이전에 저장된 검색을 찾으려면 * Saved Search * 메뉴를 사용합니다. 필요한 구성을 찾을 수 없으면 * Cannot Find Config? * 메뉴를 클릭하고 문제를 보고합니다.
