---
sidebar: sidebar 
permalink: refine-serach-page-to-verify-compatibility.html 
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, Active IQ, Interop, Advisor, tool 
summary: 상호 운용성 매트릭스 툴을 사용하면 검색 기준 구체화 페이지에서 제품에 대한 호환 구성을 탐색할 수 있습니다. 
---
= 호환성 확인을 위해 검색 기준 구체화 페이지를 참조하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
상호 운용성 매트릭스 툴을 사용하면 * 고급 검색 기준 * 페이지에서 제품에 대한 호환 구성을 탐색할 수 있습니다. 이 페이지에서 제품의 원하는 구성으로 구성 결과를 좁힐 수 있습니다.

입력한 조건에 지원되는 구성이 있는 경우에만 초기 검색 기준 페이지에서 * 검색 기준 구체화 * 페이지로 이동할 수 있습니다. 검색 기준 구체화 * 페이지는 두 개의 창으로 구분됩니다.

* * 검색 기준 *: 검색 기준에 추가된 솔루션, 구성 요소 및 필터를 표시합니다. 초기 검색 기준을 수정하여 필요한 구성 결과를 볼 수 있습니다. [기준 변경]을 선택하여 * [검색 기준] 페이지로 돌아가서 초기 검색 기준을 수정할 수 있습니다. 동적 필터링 * 탭을 선택하면 구성 요소 간의 호환성을 즉시 확인할 수 있습니다. 여러 구성 요소를 함께 추가하려면 * 동적 필터링 * 탭의 선택을 취소하고 * 업데이트 * 수를 클릭합니다. 다른 방법 시도 * 탭을 선택하여 홈 페이지로 이동할 수 있습니다.
* * 검색 기준 구체화 *: 다른 범주 아래에 구성 요소 목록을 표시합니다. 이 창에 나열된 범주는 검색 기준 및 호환 구성에 따라 달라집니다.
+
** 초기 검색 기준에 솔루션을 포함시킨 경우, 구체화 * 검색 기준 * 페이지의 특정 범주에서 구성 요소를 선택할 수 있으며 다른 범주의 구성 요소를 선택할 수 있습니다.
** 초기 검색 기준에 특정 구성 요소를 포함했으면 * 검색 기준 구체화 * 페이지의 초기 검색 기준에 포함된 구성 요소를 선택 취소할 수 없지만 다른 범주에서 추가 구성 요소를 선택할 수 있습니다.




각 범주에서 필터 아이콘을 사용하여 검색 텍스트 상자를 표시하고 특정 구성 요소를 검색할 수 있습니다. 검색 조건 * 창에서 구성 요소 선택을 재설정하거나 해제하려면 * 모두 지우기 * 를 클릭합니다.

다른 카테고리에서 선택한 부품에 따라 설정 결과의 수가 다를 수 있습니다. 더 많은 구성 요소를 선택할수록 상호 운용성 매트릭스 툴의 검색 결과가 좁아지고 제품에 대해 원하는 구성을 볼 수 있습니다.
