---
sidebar: sidebar 
permalink: saved-search-criteria-sharing-with-other-users.html 
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, Active IQ, Interop, Advisor, tool 
summary: 다른 사용자와 조건을 공유할 수 있습니다. 
---
= 저장된 검색 기준을 다른 사용자와 공유합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
검색 기준 구체화 * 페이지에서 * 저장된 검색 * 기준을 다른 사용자와 공유할 수 있습니다.

다음은 검색 기준을 저장하고 공유하는 세 가지 방법입니다.

* <<저장하는 동안 조건을 공유합니다>>
* <<저장 후 기준을 공유합니다>>
* <<공유된 기준을 봅니다>>




== 저장하는 동안 조건을 공유합니다

검색 기준 구체화 페이지에서 저장하는 동안 검색 기준을 공유할 수 있습니다.



=== 시작하기 전에

저장하는 동안 조건을 공유하려면 첫 페이지에 솔루션과 구성 요소를 추가해야 합니다.



=== 단계

. 저장된 검색 기준을 공유하려면 공유 확인란을 선택합니다.
. 사용자 검색 텍스트 상자에 사용자 이름을 입력하고 사용자 추가 를 클릭합니다.
+

NOTE: 사용자 이름이 없으면 유효성 검사 메시지가 표시됩니다.

. 검색 사용자 옵션을 사용하여 조회한 후 조건을 공유하도록 전송할 수 있습니다.




== 저장 후 기준을 공유합니다

검색 기준 구체화 페이지에서 저장 후 검색 기준을 공유할 수 있습니다.



=== 시작하기 전에

저장 후 조건을 공유하려면 첫 페이지에 저장된 검색 솔루션 및 구성 요소를 추가해야 합니다.



=== 단계

. 홈 페이지에서 저장된 검색 옵션을 클릭합니다.
. 다른 사용자와 조건을 공유하려면 공유를 클릭합니다.
. 텍스트 상자에 사용자 이름 을 입력하여 사용자를 검색하고 제출 을 클릭합니다.




== 공유된 기준을 봅니다



=== 시작하기 전에

저장된 검색에 솔루션과 구성 요소를 저장해야 합니다.



=== 단계

. 저장된 검색 옵션을 기본값으로 설정하여 다른 사용자와 공유한 조건을 볼 수 있습니다.
. 공유 기준 열에서 사용자 이름 을 선택하여 공유 기준을 표시합니다.
. 공유 사용자에게 공유에 대한 알림 전자 메일 알림이 전송됩니다.



NOTE: 원래 기준에 대한 업데이트는 공유된 기준과 아무런 관련이 없습니다. 별도의 엔터티로 간주됩니다.
