---
sidebar: sidebar 
permalink: working-with-solution-search.html 
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, storage, area, network 
summary: 다른 스토리지 솔루션을 검색하고 검색 기준에 솔루션을 추가 또는 제거할 수 있습니다. 솔루션 검색 페이지 내의 검색 텍스트 상자를 사용하여 특정 솔루션을 검색할 수 있습니다. 자주 액세스하는 솔루션이 솔루션 검색 필드에 표시됩니다. 
---
= 솔루션 검색 작업
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
다른 스토리지 솔루션을 검색하고 검색 기준에 솔루션을 추가 또는 제거할 수 있습니다. 솔루션 검색 * 페이지 내의 검색 텍스트 상자를 사용하여 특정 솔루션을 검색할 수 있습니다. 자주 액세스하는 솔루션이 * 솔루션 검색 * 필드에 표시됩니다.



== 이 작업에 대해

솔루션 검색 * 페이지에는 * 솔루션 카탈로그 * 탭과 * 매핑 도우미 * 탭이 있습니다. 매핑 도우미 * 탭에서 * 범주별 매핑 * 또는 * 솔루션별 맵 * 을 선택하여 선택한 솔루션의 범주를 볼 수 있습니다.



=== 솔루션 카탈로그

솔루션 카탈로그 * 탭에서 필터 바를 사용하여 * 솔루션 * 을 필터링할 수 있습니다.

또한, 이러한 구성을 포함하려면 * 필수 PVR, EOS 및 폐기 구성 포함 * 을 선택할 수도 있습니다.



=== 매핑 도우미

다음은 두 가지 유형의 작업 영역 모드입니다.

* *범주별 매핑*: 목록 맨 위에 유효한 솔루션이 있는 선택한 범주를 포함하는 모든 솔루션을 사용할 수 있도록 나열된 범주에서 범주를 선택할 수 있습니다. 선택한 단일 또는 여러 개의 활성화된 솔루션을 추가할 수 있습니다. 검색 범주 * 텍스트 상자를 사용하여 특정 범주를 검색할 수 있습니다.
* * 솔루션별 매핑 *: 나열된 솔루션에서 솔루션을 선택하고 선택한 솔루션이 포함된 모든 솔루션을 사용할 수 있으며, 목록 맨 위에 유효한 솔루션이 있습니다. 선택한 단일 또는 여러 개의 활성화된 솔루션을 추가할 수 있습니다. Search Solutions * 텍스트 상자를 사용하여 특정 범주를 검색할 수 있습니다.


또한, 이러한 구성을 포함하려면 * 필수 PVR, EOS 및 폐기 구성 포함 * 을 선택할 수도 있습니다.

완료되면 * Selected Storage Solutions * 아래에서 선택한 항목을 볼 수 있습니다. * 검색 기준 구체화 보기 * 또는 * 결과로 건너뛰기 * 를 클릭합니다.



=== 안내 검색

* Guided Search * 는 솔루션을 선택할 때 활성화됩니다. Guided Search * 는 기준을 더욱 구체화할 수 있는 안내 워크플로우를 제공합니다.



== 단계

. 홈 페이지에서 * 솔루션 검색 * 을 클릭합니다.
. 사용할 보기를 선택합니다.
+
.. 고급 기준 옵션을 보려면 * 전문가 보기 * 를 클릭하십시오.
.. 안내식 보기 * 를 클릭하여 단순화된 안내 기준 옵션을 확인합니다.


. 초보자 보기에서 표시되는 검색 기준 옵션을 선택합니다.
+
.. 선택하지 않고 다음 부품으로 이동하려면 * 건너뛰기 * 를 클릭합니다. 필요한 경우 * Unskip * 을 클릭하여 구성 요소로 돌아갈 수 있습니다.
.. 처음 5개 항목을 선택한 후 * 더 보기 * 를 클릭하여 검색 기준을 계속 구체화합니다. 간단히 표시 * 를 클릭하면 이전 보기로 돌아갈 수 있습니다.
.. 완료되면 * 결과 보기 * 를 클릭하여 검색 기준에 대해 지원되는 구성을 확인합니다.


. 전문가 보기 * 에서 다양한 구성 요소에 사용할 검색 기준을 선택합니다. 각 선택 항목이 나머지 기준을 구체화하므로 왼쪽에서 오른쪽으로 이동하는 것이 좋습니다. 각 부품에 대해 선택할 필요는 없습니다.
+
.. 완료되면 * 결과 보기 * 를 클릭하여 검색 기준에 대해 지원되는 구성을 확인합니다.


. 솔루션 검색 * 의 일부로 다음을 수행할 수도 있습니다.
+
.. 책 아이콘을 클릭하여 선택한 항목에 적용되는 정책 및 지침을 확인합니다.
.. 체인 아이콘을 클릭하여 다른 사용자와 공유할 수 있는 선택 항목에 대한 공유 가능한 URL을 생성합니다.
.. 실행 취소 아이콘을 선택하여 모든 선택을 취소하고 다시 시작합니다.


. 결과 화면에서 다음을 수행할 수 있습니다.
+
.. 구성에 대한 세부 정보, 경고 및 정보 알림을 봅니다.
.. 이 검색을 즐겨찾기로 설정하려면 별표 아이콘을 클릭하십시오. 구성의 이름과 설명을 지정합니다. 저장된 검색이 되며 저장된 검색 메뉴에서 볼 수 있습니다. 여기에서 구성을 구독할 수도 있습니다. 그러면 변경 사항이 발생하면 알림이 표시됩니다. 구독하는 경우 * 구독 * 메뉴 아래에 이 목록이 표시됩니다.
.. 지원되는 추가 솔루션을 찾으려면 * Build End to End View with * 를 마우스 포인터로 가리키십시오.
.. 구성 요소를 변경하고 기타 호환성 옵션을 살펴보려면 * 가상 * 을 클릭하십시오.



