---
sidebar: sidebar 
permalink: working-with-ontap-san-host-solutions-search.html 
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, storage, area, network 
summary: ONTAP 버전 및 플래시 또는 패브릭 스토리지 버전 조합의 호환성을 확인합니다. 각 관련 구성 요소에 대한 호환성 검색을 더 구체화할 수 있습니다 
---
= ONTAP SAN 호스트 간편한 검색 작업
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ONTAP 버전 및 플래시 또는 패브릭 스토리지 버전 조합의 호환성을 확인하십시오. 각 관련 구성 요소에 대한 호환성 검색을 더 구체화할 수 있습니다.



== 이 작업에 대해

SAN의 플래시 또는 패브릭 스토리지 장치와 사용하려는 ONTAP 버전 및 기타 관련 구성 요소 간의 호환성을 확인할 수 있습니다. 전문가 보기 * 또는 * 초보자 보기 * 중에서 선택할 수 있습니다.


NOTE: IMT를 열 때마다 * ONTAP SAN 호스트 간소화 * 검색을 자동으로 열려면 * 기본값으로 설정 * 옵션을 클릭합니다.



== 단계

. 홈 페이지에서 * ONTAP SAN Host Simplified * 를 클릭합니다.
. 사용할 보기를 선택합니다.
+
.. 고급 기준 옵션을 보려면 * 전문가 보기 * 를 클릭하십시오.
.. 기본 보기 * 를 클릭하면 기본 및 안내 기준 옵션이 표시됩니다.


. 초보자 보기 * 에서 표시되는 검색 기준 옵션을 선택합니다.
+
.. 선택하지 않고 다음 부품으로 이동하려면 * 건너뛰기 * 를 클릭합니다. 필요한 경우 * Unskip * 을 클릭하여 구성 요소로 돌아갈 수 있습니다.
.. 완료되면 * 결과 보기 * 를 클릭하여 검색 기준에 대해 지원되는 구성을 확인합니다.


. 전문가 보기 * 에서 다양한 구성 요소에 사용할 검색 기준을 선택합니다. 각 선택 항목이 나머지 기준을 구체화하므로 왼쪽에서 오른쪽으로 이동하는 것이 좋습니다. 각 부품에 대해 선택할 필요는 없습니다.
+
.. 완료되면 * 결과 보기 * 를 클릭하여 검색 기준에 대해 지원되는 구성을 확인합니다.


. ONTAP SAN 호스트 간소화 * 의 일부로 다음을 수행할 수도 있습니다.
+
.. 책 아이콘을 클릭하여 선택한 항목에 적용되는 정책 및 지침을 확인합니다.
.. 체인 아이콘을 클릭하여 다른 사용자와 공유할 수 있는 선택 항목에 대한 공유 가능한 URL을 생성합니다.
.. 실행 취소 아이콘을 선택하여 모든 선택을 취소하고 다시 시작합니다.


. 결과 화면에서 다음을 수행할 수 있습니다.
+
.. 구성에 대한 세부 정보, 경고 및 정보 알림을 봅니다.
.. 이 검색을 즐겨찾기로 설정하려면 별표 아이콘을 클릭하십시오. 구성의 이름과 설명을 지정합니다. 저장된 검색이 되며 * 저장된 검색 * 메뉴에서 볼 수 있습니다. 여기에서 구성을 구독할 수도 있습니다. 그러면 변경 사항이 발생하면 알림이 표시됩니다. 구독하는 경우 * 구독 * 메뉴 아래에 이 목록이 표시됩니다.
.. 지원되는 추가 솔루션을 찾으려면 * Build End to End View with * 를 마우스 포인터로 가리키십시오.
.. 구성 요소를 변경하고 기타 호환성 옵션을 살펴보려면 * 가상 * 을 클릭하십시오.



